version: '3.3.0.{build}'
image:
  - Ubuntu2004
  - Visual Studio 2019
environment:
  DOTNET_SDK: net5.0
  matrix:
    - ARCH: generic
    - ARCH: x64
matrix:
  exclude:
    - image: Ubuntu2004
      ARCH: generic
shallow_clone: true
pull_requests:
  do_not_increment_build_number: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
deploy:
  - provider: GitHub
    artifact: archive
    draft: false
    prerelease: false
    auth_token:
      secure: s4KrkEh5TVzLxfOWeChe1mpLRpdh9OWjlZmFBV/rxEpaA2SQmxW59s0aQzGBaiJH
    on:
      APPVEYOR_REPO_TAG: true
for:
  -
    matrix:
      only:
        - ARCH: generic
    skip_non_tags: true
    build_script:
      - pwsh: dotnet publish -c Release
    after_build:
      - pwsh: Remove-Item .\bin\Release\net5.0\publish\*.pdb
      - pwsh: >-
          if ($env:APPVEYOR_REPO_TAG_NAME -eq $null) { $env:APPVEYOR_REPO_TAG_NAME = 'snapshot' }
          7z a "MusicDecrypto-net5.0-generic-$env:APPVEYOR_REPO_TAG_NAME.7z" .\bin\Release\net5.0\publish\*;
          (Get-FileHash "MusicDecrypto-net5.0-generic-$env:APPVEYOR_REPO_TAG_NAME.7z" SHA256).Hash + " MusicDecrypto-net5.0-generic-$env:APPVEYOR_REPO_TAG_NAME.7z" > "MusicDecrypto-net5.0-generic-$env:APPVEYOR_REPO_TAG_NAME.7z.sha256"
    artifacts:
      - path: '*.7z*'
        name: archive
  -
    matrix:
      only:
        - image: Ubuntu2004
    install:
      - sudo apt-get update && sudo apt-get -y install libkrb5-dev
    before_build:
      - dotnet add package Microsoft.DotNet.ILCompiler -v 6.0.0-*
    build_script:
      - dotnet publish -r linux-x64 -c Release /p:IlcInvariantGlobalization=true /p:IlcGenerateCompleteTypeMetadata=false /p:IlcGenerateStackTraceData=false
    after_build:
      - strip ./bin/Release/net5.0/linux-x64/publish/MusicDecrypto
      - pwsh: if ($env:APPVEYOR_REPO_TAG_NAME -eq $null) { $env:APPVEYOR_REPO_TAG_NAME = 'snapshot' }
      - tar czvf "MusicDecrypto-linux-x64-$APPVEYOR_REPO_TAG_NAME.tar.gz" -C "./bin/Release/net5.0/linux-x64/publish" MusicDecrypto
      - sha256sum "MusicDecrypto-linux-x64-$APPVEYOR_REPO_TAG_NAME.tar.gz" > "MusicDecrypto-linux-x64-$APPVEYOR_REPO_TAG_NAME.tar.gz.sha256"
    artifacts:
      - path: '*.gz*'
        name: archive
  -
    matrix:
      only:
        - image: Visual Studio 2019
    before_build:
      - dotnet add package Microsoft.DotNet.ILCompiler -v 6.0.0-*
    build_script:
      - dotnet publish -r win-x64 -c Release /p:IlcInvariantGlobalization=true /p:IlcGenerateCompleteTypeMetadata=false /p:IlcGenerateStackTraceData=false
    after_build:
      - pwsh: >-
          if ($env:APPVEYOR_REPO_TAG_NAME -eq $null) { $env:APPVEYOR_REPO_TAG_NAME = 'snapshot' }
          7z a "MusicDecrypto-win-x64-$env:APPVEYOR_REPO_TAG_NAME.7z" .\bin\Release\net5.0\win-x64\publish\MusicDecrypto.exe;
          (Get-FileHash "MusicDecrypto-win-x64-$env:APPVEYOR_REPO_TAG_NAME.7z" SHA256).Hash + " MusicDecrypto-win-x64-$env:APPVEYOR_REPO_TAG_NAME.7z" > "MusicDecrypto-win-x64-$env:APPVEYOR_REPO_TAG_NAME.7z.sha256"
    artifacts:
      - path: '*.7z*'
        name: archive
