version: '3.1.0.{build}'
image:
  - Ubuntu
  - Visual Studio 2019
shallow_clone: true
pull_requests:
  do_not_increment_build_number: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - dotnet add package Microsoft.DotNet.ILCompiler -v 6.0.0-*
for:
  -
    matrix:
      only:
        - image: Ubuntu
    install:
      - sudo apt-get update && sudo apt-get -y install libkrb5-dev
    build_script:
      - dotnet publish -c Release -r linux-x64 /p:IlcInvariantGlobalization=true /p:IlcGenerateCompleteTypeMetadata=false /p:IlcGenerateStackTraceData=false
    after_build:
      - pwsh: >-
          strip ./bin/Release/net5.0/linux-x64/publish/MusicDecrypto;
          if ($env:APPVEYOR_REPO_TAG_NAME -eq $null) { $env:APPVEYOR_REPO_TAG_NAME = 'snapshot' }
          $archive = 'MusicDecrypto-linux-x64-' + $env:APPVEYOR_REPO_TAG_NAME + '.tar.gz';
          tar czvf $archive -C ./bin/Release/net5.0/linux-x64/publish MusicDecrypto;
          (Get-FileHash -Algorithm SHA256 $archive).Hash.ToString().ToLower() > ($archive + '.sha256')
    artifacts:
      - path: '*.gz*'
        name: linux-x64
    deploy:
      - provider: GitHub
        artifact: linux-x64
        draft: false
        prerelease: false
        auth_token:
          secure: s4KrkEh5TVzLxfOWeChe1mpLRpdh9OWjlZmFBV/rxEpaA2SQmxW59s0aQzGBaiJH
        on:
          APPVEYOR_REPO_TAG: true
  -
    matrix:
      only:
        - image: Visual Studio 2019
    build_script:
      - dotnet publish -c Release -r win-x64 /p:IlcInvariantGlobalization=true /p:IlcGenerateCompleteTypeMetadata=false /p:IlcGenerateStackTraceData=false
    after_build:
      - pwsh: >-
          if ($env:APPVEYOR_REPO_TAG_NAME -eq $null) { $env:APPVEYOR_REPO_TAG_NAME = 'snapshot' }
          $archive = 'MusicDecrypto-win-x64-' + $env:APPVEYOR_REPO_TAG_NAME + '.7z';
          7z a $archive .\bin\Release\net5.0\win-x64\publish\MusicDecrypto.exe;
          (Get-FileHash -Algorithm SHA256 $archive).Hash.ToString().ToLower() > ($archive + '.sha256')
    artifacts:
      - path: '*.7z*'
        name: win-x64
    deploy:
      - provider: GitHub
        artifact: win-x64
        draft: false
        prerelease: false
        auth_token:
          secure: s4KrkEh5TVzLxfOWeChe1mpLRpdh9OWjlZmFBV/rxEpaA2SQmxW59s0aQzGBaiJH
        on:
          APPVEYOR_REPO_TAG: true
