version: '2.1.0.{build}'
image: Visual Studio 2019
shallow_clone: true
pull_requests:
  do_not_increment_build_number: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - nuget install Microsoft.Packaging.Tools.Trimming -OutputDirectory packages -Version 1.1.0-preview1-26619-01
  - nuget install CommandLineParser -OutputDirectory packages -Version 2.6.0
  - nuget install Newtonsoft.Json -OutputDirectory packages -Version 12.0.3
  - nuget install TagLibSharp -OutputDirectory packages -Version 2.2.0
build_script:
  - dotnet publish -c Release
  - dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true
after_build:
  - 7z a MusicDecrypto-netcore3.1-generic.7z .\bin\Release\netcoreapp3.1\publish\*.exe .\bin\Release\netcoreapp3.1\publish\*.dll .\bin\Release\netcoreapp3.1\publish\*.json
  - 7z a MusicDecrypto-netcore3.1-win64.7z .\bin\Release\netcoreapp3.1\win-x64\publish\*.exe
artifacts:
  - path: MusicDecrypto-netcore3.1-generic.7z
    name: generic
  - path: MusicDecrypto-netcore3.1-win64.7z
    name: win64
deploy:
  - provider: GitHub
    artifact: generic,win64
    draft: false
    prerelease: false
    auth_token:
      secure: s4KrkEh5TVzLxfOWeChe1mpLRpdh9OWjlZmFBV/rxEpaA2SQmxW59s0aQzGBaiJH
    on:
      APPVEYOR_REPO_TAG: true
